// GENERATED by scripts/build-hs-photos.mjs from design/assets/products/hs/manifest.json
// (queried 2026-09-18). Do not edit by hand; re-run the script.
//
// One row per 4-digit EPB HS heading in the photo catalogue. `exporters` is the
// count of Bangladeshi exporters on the EPB list for that heading at query time,
// used to order a supplier's lines rarest-first. `hasPhoto` is whether
// public/products/hs/hs-<code>.webp exists; a heading without one renders its
// code, never a substitute photo.

export type HsCatalogueRow = {
  hs: string;
  short: string;
  heading: string;
  exporters: number;
  hasPhoto: boolean;
};

export const HS_CATALOGUE: readonly HsCatalogueRow[] = [
  { hs: "4202", short: "Bags, cases", heading: "Trunks, suit-cases, handbags and similar containers", exporters: 74, hasPhoto: true },
  { hs: "6001", short: "Pile fabrics", heading: "Pile fabrics, knitted or crocheted", exporters: 37, hasPhoto: true },
  { hs: "6006", short: "Knitted fabrics", heading: "Other knitted or crocheted fabrics", exporters: 22, hasPhoto: true },
  { hs: "6101", short: "Men's knitted coats", heading: "Men's or boys' overcoats and similar articles, knitted or crocheted", exporters: 1520, hasPhoto: true },
  { hs: "6102", short: "Women's knitted coats", heading: "Women's or girls' overcoats and similar articles, knitted or crocheted", exporters: 1526, hasPhoto: true },
  { hs: "6103", short: "Men's knitted suits", heading: "Men's or boys' suits, ensembles, etc, knitted or crocheted", exporters: 1713, hasPhoto: true },
  { hs: "6104", short: "Women's knitted suits", heading: "Women's or girls' suits, ensembles, etc, knitted or crocheted", exporters: 1799, hasPhoto: true },
  { hs: "6105", short: "Men's knitted shirts", heading: "Men's or boys' shirts, knitted or crocheted", exporters: 1635, hasPhoto: true },
  { hs: "6106", short: "Women's blouses", heading: "Women's or girls' blouses, etc, knitted or crocheted", exporters: 1567, hasPhoto: true },
  { hs: "6107", short: "Men's underwear", heading: "Men's or boys' briefs and similar articles, knitted or crocheted", exporters: 1541, hasPhoto: true },
  { hs: "6108", short: "Women's nightwear", heading: "Women's or girls' panties and similar articles, knitted or crocheted", exporters: 1539, hasPhoto: true },
  { hs: "6109", short: "T-shirts, vests", heading: "T-shirts, singlets and other vests, knitted or crocheted", exporters: 1764, hasPhoto: true },
  { hs: "6110", short: "Pullovers, cardigans", heading: "Jerseys, pullovers, cardigans and similar articles, knitted or crocheted", exporters: 1778, hasPhoto: true },
  { hs: "6111", short: "Babies' garments", heading: "Babies' garments and clothing accessories, knitted or crocheted", exporters: 1638, hasPhoto: true },
  { hs: "6112", short: "Tracksuits, swimwear", heading: "Track-suits, ski-suits and swimwear, knitted or crocheted", exporters: 1303, hasPhoto: true },
  { hs: "6113", short: "Coated knit garments", heading: "Garments made up of coated knitted fabrics", exporters: 1002, hasPhoto: true },
  { hs: "6114", short: "Other knitwear", heading: "Other garments, knitted or crocheted, nes", exporters: 1259, hasPhoto: true },
  { hs: "6115", short: "Socks, hosiery", heading: "Panty hose, tights, etc, and footwear, knitted or crocheted", exporters: 954, hasPhoto: true },
  { hs: "6116", short: "Knitted gloves", heading: "Gloves, mittens and mitts, knitted or crocheted", exporters: 834, hasPhoto: true },
  { hs: "6117", short: "Knitted accessories", heading: "Other made up clothing accessories, knitted or crocheted", exporters: 1005, hasPhoto: true },
  { hs: "6201", short: "Men's coats, parkas", heading: "Men's or boys' overcoats and similar articles", exporters: 1201, hasPhoto: true },
  { hs: "6202", short: "Women's coats", heading: "Women's or girls' overcoats and similar articles", exporters: 1198, hasPhoto: true },
  { hs: "6203", short: "Men's suits, trousers", heading: "Men's or boys' suits, jackets, trousers", exporters: 1408, hasPhoto: true },
  { hs: "6204", short: "Women's dresses, suits", heading: "Women's or girls' suits, jackets, dresses, skirts", exporters: 1423, hasPhoto: true },
  { hs: "6205", short: "Men's woven shirts", heading: "Men's or boys' shirts", exporters: 1339, hasPhoto: true },
  { hs: "6206", short: "Women's woven blouses", heading: "Women's or girls' blouses, shirts and shirt-blouses", exporters: 1275, hasPhoto: true },
  { hs: "6207", short: "Men's nightwear", heading: "Men's or boys' underpants, nightshirts, pyjamas", exporters: 1142, hasPhoto: true },
  { hs: "6208", short: "Women's slips, pyjamas", heading: "Women's or girls' slips, nightdresses, pyjamas", exporters: 1113, hasPhoto: true },
  { hs: "6209", short: "Babies' woven wear", heading: "Babies' garments and clothing accessories", exporters: 1186, hasPhoto: true },
  { hs: "6210", short: "Coated garments", heading: "Garments made up of coated or non-woven fabrics", exporters: 911, hasPhoto: true },
  { hs: "6211", short: "Track suits, swimwear", heading: "Track suits, ski suits and swimwear, not knitted", exporters: 1129, hasPhoto: true },
  { hs: "6212", short: "Bras, girdles", heading: "Brassieres, girdles, corsets, braces, suspenders", exporters: 810, hasPhoto: true },
  { hs: "6213", short: "Handkerchiefs", heading: "Handkerchiefs", exporters: 631, hasPhoto: true },
  { hs: "6214", short: "Scarves, shawls", heading: "Shawls, scarves, mufflers, veils and the like", exporters: 707, hasPhoto: true },
  { hs: "6215", short: "Ties", heading: "Ties, bow ties and cravats", exporters: 659, hasPhoto: true },
  { hs: "6216", short: "Woven gloves", heading: "Gloves, mittens and mitts", exporters: 599, hasPhoto: true },
  { hs: "6217", short: "Other accessories", heading: "Other made up clothing accessories; parts of garments", exporters: 629, hasPhoto: true },
  { hs: "6301", short: "Blankets", heading: "Blankets and travelling rugs", exporters: 56, hasPhoto: true },
  { hs: "6302", short: "Bed, table linen", heading: "Bed linen, table linen, toilet linen and kitchen linen", exporters: 54, hasPhoto: true },
  { hs: "6303", short: "Curtains, blinds", heading: "Curtains, interior blinds, valances", exporters: 20, hasPhoto: true },
  { hs: "6304", short: "Furnishing articles", heading: "Other furnishing articles", exporters: 34, hasPhoto: true },
  { hs: "6305", short: "Sacks, packing bags", heading: "Sacks and bags, used for packing goods", exporters: 70, hasPhoto: true },
  { hs: "6307", short: "Other made-up articles", heading: "Other made up articles", exporters: 103, hasPhoto: true },
  { hs: "6504", short: "Plaited hats", heading: "Hats and other headgear, plaited", exporters: 30, hasPhoto: true },
  { hs: "6505", short: "Knitted hats", heading: "Hats and other headgear, knitted or crocheted", exporters: 462, hasPhoto: true },
  { hs: "6506", short: "Other headgear", heading: "Other headgear", exporters: 22, hasPhoto: true },
];
