// The HS photo catalogue as the dashboard uses it (handoff §6, REZ-A).
//
// Photos are keyed to the 4-digit EPB HS heading and shared by every supplier
// who exports that line, so neighbouring cards do not all lead with the same
// navy polo: a supplier's strip shows its least-common lines first, by exporter
// count on EPB. A heading without a photo keeps its place and shows its code —
// nothing is substituted. The photo files and `HS_CATALOGUE` are generated by
// `scripts/build-hs-photos.mjs`.

import { HS_CATALOGUE, type HsCatalogueRow } from "@/lib/hs-catalogue";
import { hsBuyerLabel } from "@/lib/epb-hscode-labels";

const BY_CODE: ReadonlyMap<string, HsCatalogueRow> = new Map(HS_CATALOGUE.map((r) => [r.hs, r]));

/** The catalogue row for a heading, or null when the heading is not in the catalogue. */
export function hsCatalogueRow(code: string): HsCatalogueRow | null {
  return BY_CODE.get(heading4(code)) ?? null;
}

/** `610510` → `6105`; a 4-digit code is returned as-is. */
export function heading4(code: string): string {
  return code.trim().slice(0, 4);
}

/** Path of the illustrative photo under /public, or null when the heading has none. */
export function hsPhotoSrc(code: string, size: 512 | 128 = 512): string | null {
  const row = hsCatalogueRow(code);
  if (!row || !row.hasPhoto) return null;
  return size === 512 ? `/products/hs/hs-${row.hs}.webp` : `/products/hs/hs-${row.hs}-${size}.webp`;
}

/** The short caption that fits a 132px tile at 12px (the manifest's `short`), else the buyer label. */
export function hsShortLabel(code: string, description: string | null = null): string {
  const row = hsCatalogueRow(code);
  return row?.short ?? hsBuyerLabel(heading4(code), description);
}

/** Number of exporters on EPB for the heading; a heading outside the catalogue counts as rarest. */
export function hsExporterCount(code: string): number {
  return hsCatalogueRow(code)?.exporters ?? 0;
}

/**
 * A supplier's lines, least-common first, deduplicated to 4-digit headings.
 * Ties break on the code so the order is stable from render to render.
 */
export function rarestFirst(codes: readonly string[], n?: number): string[] {
  const seen = new Set<string>();
  const headings: string[] = [];
  for (const c of codes) {
    const h = heading4(c);
    if (!/^\d{4}$/.test(h) || seen.has(h)) continue;
    seen.add(h);
    headings.push(h);
  }
  headings.sort((a, b) => hsExporterCount(a) - hsExporterCount(b) || a.localeCompare(b));
  return typeof n === "number" ? headings.slice(0, n) : headings;
}

export type PhotoTileModel = {
  hs: string;
  /** Short heading for the caption. */
  short: string;
  /** Photo path at 512px, or null → the tile shows the code and "no photo yet". */
  src: string | null;
  /** Photo path at 128px for table thumbs. */
  thumb: string | null;
};

/** Tile models for a strip or grid: the `n` rarest lines of the supplier. */
export function photoTiles(codes: readonly string[], n: number): PhotoTileModel[] {
  return rarestFirst(codes, n).map((hs) => ({
    hs,
    short: hsShortLabel(hs),
    src: hsPhotoSrc(hs, 512),
    thumb: hsPhotoSrc(hs, 128),
  }));
}
